### ISSUE TITLE
Do we want to queue usercode?

### ISSUE THREAD

**Issue by trickeydan** [trickeydan/pepper2#22]
This assumes that only ONE usercode can be run at a time.

If multiple usercode USBs are inserted, do we:

- Ignore additional USBs (Current Behaviour)
- Queue additional USBs to be executed after the preceding code
- Override to the new USB
- Error and do nothing (Probably not)

**Comment by trickeydan** [comment]
@kierdavis @mildlyincompetent

**Comment by RealOrangeOne** [comment]
The way it works now sounds fine to me.
